export const environment = {
    logInByEmail: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/mail/logInByMail",
    googleLogIn: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/login/google",
    getusuariosSignUp: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios",
    postNewUserSignUp: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios",
    getUserByIDUsers: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios/",
    putUserByID: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios/",
    getUsuarioByIDUsuario: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios/",
    getUsuarios: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/usuarios",
    putResponseResponse: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/comentarios/",
    publicacionesURL: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/publicaciones/",
    postURL: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/publicaciones",
    getNegociosByIDNegocios: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/negocios/",
    postNegocioNegocios: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/negocios",
    commentByIDComment: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/comentarios/",
    getPostCommentCOmments: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/comentarios",
    CRUDNegociosByID: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/negocios/",
    postNewBusiness: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/negocios",
    getCommentsFromBCommentsServiceService: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/comentarios/negocio/",
    getCommentByIDCommentsServiceService: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/comentarios/",
    businessPictureUpload: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/uploadBusinessPictures",
    googleProviderID: "311546582233-9bidftbrtt8e4setlvdqrg2q2gngjbji.apps.googleusercontent.com",
    apiUrl: "http://foodcentralapiserver-env.eba-jwej3m7t.us-east-1.elasticbeanstalk.com/"
};
